services:
  # NOTE: containers have network_mode=host for development reasons, without it i cannot access to the department sensor data via VPN
  nodered:
    image: nodered/node-red:5.0
    container_name: nodered
    environment:
      - FLOWS=flows.json
      # Forza l'indirizzo con il protocollo in chiaro
      - ZEEBE_GRPC_ADDRESS=grpc://127.0.0.1:26500
      # Disabilita esplicitamente la richiesta di certificati TLS/SSL
      - ZEEBE_INSECURE_CONNECTION=true
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
      - ./:/data/host_files
      - ./node_red_data:/data
    network_mode: host

    restart: "no"

  redis:
    image: redis:8.2
    container_name: redis
    network_mode: host
    ports:
      - "6379:6379"
    restart: "no"

  memgraph-mage:
    image: memgraph/memgraph-mage:3.12.0
    container_name: memgraph-mage
    # network_mode: host
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    command: [ "--log-level=TRACE" ]

  lab:
    image: memgraph/lab:3.12.0
    container_name: memgraph-lab
    network_mode: host
    ports:
      - "3000:3000"
    depends_on:
      - memgraph-mage
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

  thingsboard-mcp:
    image: thingsboard/mcp:2.1.0
    container_name: thingsboard-mcp
    network_mode: host
    ports:
      - "8000:8000"
    # stdin_open: true
    environment:
      THINGSBOARD_URL: "http://193.205.92.195:8080"
      THINGSBOARD_USERNAME: "tenant@thingsboard.org"
      THINGSBOARD_PASSWORD: "tenant"

      THINGSBOARD_TOOLS_TELEMETRY: "true"
      THINGSBOARD_TOOLS_DEVICE: "true"
      THINGSBOARD_TOOLS_ALARM: "true"
      THINGSBOARD_TOOLS_EDQ: "true"
      THINGSBOARD_TOOLS_ASSET: "true"
      THINGSBOARD_TOOLS_RELATION: "true"

      THINGSBOARD_TOOLS_CUSTOMER: "false"
      THINGSBOARD_TOOLS_USER: "false"
      THINGSBOARD_TOOLS_OTA: "false"
      THINGSBOARD_TOOLS_GROUP: "false"
      # for sse connection
      SPRING_AI_MCP_SERVER_STDIO: "false"
      SPRING_WEB_APPLICATION_TYPE: "servlet"

  memgraph-mcp:
    image: memgraph/mcp-memgraph:0.2.0
    container_name: memgraph-mcp
    # network_mode: host
    ports:
      - "8001:8000"
    # stdin_open: true
    environment:
      MEMGRAPH_URL: "bolt://memgraph-mage:7687"
      MCP_TRANSPORT: "streamable-http"
      MCP_READ_ONLY: "true"
      MCP_SERVER: "server"

volumes:
  node_red_data:

  mg_lib:
  mg_log:
  mg_etc:
