global_settings:
  cache_threshold_percent: 0.05 # fallback threshold for sensor data changes (5%)
  ttl_seconds: 300  # time to live for the cached data in seconds
  retention_ms: 300000 # 5 minues
  excluded_sensors:
    - light

danger_tiers:
  high: 1
  medium: 2
  low: 3

departments:
  departmentA:
    - name: AA1
      sensors: ["AA1-01", "AA1-02"]
    - name: AB1
      sensors: ["AB1-01"]
    - name: AB2
      sensors: ["AB2-01", "AB2-02"]
    - name: LA1
      sensors: ["LA1-01", "LA1-02"]
    - name: StanzaCulmone
      sensors: ["StanzaCulmone"]
    - name: StanzaDocente
      sensors: ["StanzaDocente"]
    - name: TeamLab
      sensors: ["TeamLab-01", "TeamLab-02"]
  departmentB:
    - name: B1
      sensors: ["B1-01", "B1-03"]
    - name: LB1
      sensors: ["LB1-01"]
    - name: SalaRiunioni
      sensors: ["SalaRiunioni"]

sensor_configs:
  # bucket_ms: the time window in milliseconds for aggregating data
  # agg_type: the aggregation type (mean, geometricMean, harmonicMean, median, min, max, sum)
  # threshold_type: the type of threshold (percentage, absolute)
  # threshold_value: the value of the threshold (percentage, absolute, always)
  temperature:
    bucket_ms: 60000
    agg_type: mean
    threshold_type: always

    # threshold_type: percentage
    # threshold_value: 0.04   # 4%
  co2:
    bucket_ms: 60000
    agg_type: max
    threshold_type: always
    # threshold_type: absolute
    # threshold_value: 10     # +/- 10 ppm
  humidity:
    agg_type: max
    bucket_ms: 60000
    threshold_type: always
  tvoc:
    agg_type: max
    bucket_ms: 60000
    threshold_type: always
  eco2:
    agg_type: max
    bucket_ms: 60000
    threshold_type: always
  people_count:
    agg_type: max
    bucket_ms: 60000
    threshold_type: always
