parameters:
  temperature:
    agg_type: max
    bucket_ms: 60000
  humidity:
    agg_type: max
    bucket_ms: 60000
  co2:
    agg_type: max
    bucket_ms: 60000
  tvoc:
    agg_type: max
    bucket_ms: 60000
  eco2:
    agg_type: max
    bucket_ms: 60000
  people_count:
    agg_type: max
    bucket_ms: 60000
